BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Movie";
CREATE TABLE IF NOT EXISTS "Movie" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Title"	TEXT,
	"ReleaseDate"	TEXT NOT NULL,
	"Genre"	TEXT,
	"Price"	TEXT NOT NULL
);
INSERT INTO "Movie" ("Id","Title","ReleaseDate","Genre","Price") VALUES (1,'Software','2019-06-03 00:00:00','Drama','20.0');
COMMIT;
